name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Chequear el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar dependencias (en la raíz, si package.json está allí)
      - name: Install dependencies
        run: npm install

      # Paso 3: Construir el proyecto Angular
      - name: Build Angular App
        run: npm run build --base-href='/'

      # Paso 4: Copiar los archivos generados al servidor remoto mediante SCP
      - name: Copy build to remote server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          echo "Added ${{ secrets.REMOTE_HOST }} to known_hosts."
          # Se asume que angular.json define "outputPath": "dist/recipes-paula"
          sshpass -p "${REMOTE_PASSWORD}" scp -r dist/recipes-paula/* ${REMOTE_USER}@${REMOTE_HOST}:/var/www/html
